--LAB-5--

CREATE TABLE STUDENT
(STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(50),
CITY VARCHAR(25),
ADDRESS VARCHAR(100));

SELECT * FROM STUDENT

 INSERT INTO STUDENT VALUES(1011, 'KEYUR', 'PATEL', 'TECHONTHENET.COM', 'RAJKOT', 'A-303 "VASANT KUNJ" RAJKOT')

INSERT INTO STUDENT VALUES(1022, 'HARDIK', 'SHAH', 'DIGMINECRAFT.COM', 'AHMEDABAD', '"RAM KRUPA" RAIYA ROAD')

INSERT INTO STUDENT VALUES(1033, 'KAJAL', 'TRIVEDI', 'BIGACTIVITIES.COM', 'BARODA', 'RAJ BHAVAN PLOT NEAR GARDEN')

INSERT INTO STUDENT VALUES(1044, 'BHOOMI', 'GAJERA', 'CHECKYOURMATH.COM', 'AHMEDABAD', ' "JIG�S HOME" NAROL ')

INSERT INTO STUDENT VALUES(1055, 'HARMIT', 'MITEL', '@ME.DARSHAN.COM', 'RAJKOT', 'B-55 RAJ RESIDENCY')

INSERT INTO STUDENT VALUES(1066, 'ASHOK', 'JANI', NULL, 'BARODA', 'A502 CLUB HOUSE BUILDING')


---5-1---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K%'

---5-2---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '_____'

---5-3---
SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE '_____A'

---5-4---
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE '%TEL'

---5-5---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'HA%T'

---5-6---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'K_Y%'

---5-7---
SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

---5-8---
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE '%JER'

---5-9---
SELECT FIRSTNAME FROM STUDENT WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'

SELECT FIRSTNAME FROM STUDENT WHERE CITY LIKE '[R,B]%'

---5-10---
SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NOT NULL

---5-11---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE '[A-H]%'                            

---5-12---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME = '_[A,E,I,O,U]%'

---5-13---
SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____%'

---5-14---
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE '%PAT'

---5-15---
SELECT FIRSTNAME FROM STUDENT WHERE CITY NOT LIKE 'B%'







---5-B-1---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE 'A%' OR FIRSTNAME LIKE 'H%'

---5-B-2---
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME = '_[A,E,I,O,U]%' OR FIRSTNAME ='H%'