CREATE TABLE  SALES_DATA
(
	Region VARCHAR(50),
	Product VARCHAR(25),
	Sales_Amount INT,
	 Year	INT
)

INSERT INTO SALES_DATA
VALUES
('North America', 'Watch', 1500,2023),
('Europe', 'Mobile', 1200, 2023),
('Asia', 'Watch', 1800, 2023),
('North America', 'TV' ,900 ,2024),
('Europe', 'Watch', 2000 ,2024),
('Asia', 'Mobile', 1000, 2024),
('North America', 'Mobile', 1600, 2023),
('Europe', 'TV', 1500, 2023),
('Asia', 'TV', 1100, 2024),
('North America', 'Watch', 1700, 2024) 	

SELECT * FROM SALES_DATA
--1--

SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL
FROM SALES_DATA
GROUP BY REGION

--2--

SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVERAGE
FROM SALES_DATA
GROUP BY PRODUCT

--3--

SELECT YEAR,MAX(SALES_AMOUNT) AS MAX
FROM SALES_DATA
GROUP BY YEAR

--4--

SELECT REGION,COUNT(PRODUCT) AS COUNT
FROM SALES_DATA
GROUP BY REGION

--5--

SELECT COUNT(PRODUCT) AS COUNT
FROM SALES_DATA
GROUP BY REGION

--6--

SELECT SUM(Sales_Amount) AS DISPLAY
FROM SALES_DATA
GROUP BY YEAR,PRODUCT

--7--
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL
FROM SALES_DATA
GROUP BY REGION
HAVING SUM(SALES_AMOUNT) < 5000


--8--

SELECT PRODUCT,AVG(SALES_AMOUNT) AS AVG
FROM SALES_DATA
GROUP BY PRODUCT
HAVING AVG(SALES_AMOUNT) < 10000

--9--

SELECT YEAR,MAX(SALES_AMOUNT) AS TOTAL
FROM SALES_DATA
GROUP BY YEAR
HAVING MAX(SALES_AMOUNT) > 500


--10--

SELECT REGION,COUNT(DISTINCT PRODUCT) AS COUNT
FROM SALES_DATA
GROUP BY REGION 
HAVING COUNT(DISTINCT PRODUCT)>=3


--11--

SELECT YEAR,MIN(SALES_AMOUNT) AS TOTAL
FROM SALES_DATA
GROUP BY YEAR
HAVING MIN(SALES_AMOUNT) < 1000

--12--

SELECT REGION,SUM(SALES_AMOUNT) AS SUM
FROM SALES_DATA
WHERE YEAR = 2023
GROUP BY REGION
ORDER BY SUM(SALES_AMOUNT)






----------------------B----------------------

--1--

SELECT COUNT(YEAR,REGION)