CREATE TABLE CRICKET
(NAME VARCHAR(50),  CITY VARCHAR(50), AGE INT)

INSERT INTO CRICKET VALUES('Sachin Tendulkar',' Mumbai', 30)
INSERT INTO CRICKET VALUES('Rahul Dravid',' Bombay', 35)
INSERT INTO CRICKET VALUES('M. S. Dhoni',' Jharkhand',31)
INSERT INTO CRICKET VALUES('Suresh Raina',' Gujarat', 30)

SELECT * FROM CRICKET

--LAB-3--
--A1--

SELECT * INTO WORLDCUP FROM CRICKET

--A2--

SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=0  

--A3--

SELECT * INTO IPL FROM CRICKET WHERE 1=0


CREATE TABLE EMPLOYEE
(NAME VARCHAR(50),  CITY VARCHAR(50), AGE INT)

INSERT INTO EMPLOYEE VALUES('Jay Patel',' Rajkot', 30)
INSERT INTO EMPLOYEE VALUES('Rahul Dave',' Baroda', 35)
INSERT INTO EMPLOYEE VALUES('Jeet Patel',' Surat', 31)
INSERT INTO EMPLOYEE VALUES('Vijay Raval','Rajkot', 30)

SELECT * FROM EMPLOYEE

--B1--

SELECT NAME,CITY,AGE INTO EMPLOYEE_DETAIL FROM EMPLOYEE

--B2--

SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE WHERE 1=0

--B3--

SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=0

--C1--

INSERT INTO EMPLOYEE_INFO 
SELECT * FROM EMPLOYEE WHERE CITY=' RAJKOT' 

SELECT * FROM EMPLOYEE_INFO

--C2--

INSERT INTO EMPLOYEE_INFO 
SELECT * FROM EMPLOYEE WHERE AGE>32

SELECT * FROM EMPLOYEE_INFO


---LAB-3(UPDATED)---

UPDATE DEPOSIT 
SET AMOUNT=5000 
WHERE AMOUNT=3000

SELECT * FROM DEPOSIT

UPDATE BORROW
SET BNAME='C.G.ROAD'
WHERE CNAME='ANIL' AND BNAME=' VRCE' 


SELECT * FROM BORROW

UPDATE DEPOSIT
SET ACTNO=111, AMOUNT = 5000
WHERE CNAME='SANDIP'

SELECT * FROM DEPOSIT

UPDATE DEPOSIT
SET AMOUNT=7000
WHERE CNAME = 'KRANTI'

SELECT * FROM DEPOSIT

UPDATE BRANCH
SET BNAME='ANDHERI WEST'
WHERE BNAME='ANDHERI'

SELECT * FROM BRANCH


