--LAB 10 (IMPLEMENT SQL VIEW)

--PART – A:

	--VIEWS (FIRST CREATE A VIEW THEN DISPLAY ALL VIEWS)

	--1. CREATE A VIEW PERSONAL WITH ALL COLUMNS.
		 	
	--2. CREATE A VIEW STUDENT_DETAILS HAVING COLUMNS NAME, BRANCH & SPI.

	--3. CREATE A VIEW ACADEMICDATA HAVING COLUMNS RNO, NAME, BRANCH.

	--4. CREATE A VIEW STUDENT_ BKLOG HAVING ALL COLUMNS BUT STUDENTS WHOSE BKLOG MORE THAN 2.

	--5. CREATE A VIEW STUDENT_PATTERN HAVING RNO, NAME & BRANCH COLUMNS IN WHICH NAME CONSISTS OF FOUR LETTERS.

	--6. INSERT A NEW RECORD TO ACADEMICDATA VIEW. (107, MEET, ME)

	--7. UPDATE THE BRANCH OF AMIT FROM CE TO ME IN STUDENT_DETAILS VIEW.

	--8. DELETE A STUDENT WHOSE ROLL NUMBER IS 104 FROM ACADEMICDATA VIEW.


--PART – B:


	--1. CREATE A VIEW THAT DISPLAYS INFORMATION OF ALL STUDENTS WHOSE SPI IS ABOVE 8.5

	--2. CREATE A VIEW THAT DISPLAYS 0 BACKLOG STUDENTS.

	--3. CREATE A VIEW COMPUTERVIEW THAT DISPLAYS CE BRANCH DATA ONLY.

--PART – C:


	--1. CREATE A VIEW RESULT_EC THAT DISPLAYS THE NAME AND SPI OF STUDENTS WITH SPI LESS THAN 5 OF BRANCH EC.

	--2. UPDATE THE RESULT OF STUDENT MAHESH TO 4.90 IN RESULT_EC VIEW.

	--3. CREATE A VIEW STU_BKLOG WITH RNO, NAME AND BKLOG COLUMNS IN WHICH NAME STARTS WITH ‘M’ AND HAVING BKLOGS MORE THAN 5.

	--4. DROP COMPUTERVIEW FORM THE DATABASE.

