--LAB 12 (IMPLEMENT COMPLEX JOINS)

--CREATE FOLLOWING TABLE (USING DESIGN MODE)

--FROM THE ABOVE GIVEN TABLE PERFORM THE FOLLOWING QUERIES:

--PART – A:

	--1. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME & CODE.

	--2. FIND THE PERSON'S NAME WHOSE DEPARTMENT IS IN C-BLOCK.

	--3. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO BELONGS TO JAMNAGAR CITY.

	--4. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO DOES NOT BELONG TO RAJKOT CITY.

	--5. RETRIEVE PERSON’S NAME OF THE PERSON WHO JOINED THE CIVIL DEPARTMENT AFTER 1-AUG-2001.

	--6. FIND DETAILS OF ALL PERSONS WHO BELONG TO THE COMPUTER DEPARTMENT.

	--7. DISPLAY ALL THE PERSON'S NAME WITH THE DEPARTMENT WHOSE JOINING DATE DIFFERENCE WITH THE CURRENT DATE IS MORE THAN 365 DAYS.

	--8. FIND DEPARTMENT WISE PERSON COUNTS.

	--9. GIVE DEPARTMENT WISE MAXIMUM & MINIMUM SALARY WITH DEPARTMENT NAME.

	--10. FIND CITY WISE TOTAL, AVERAGE, MAXIMUM AND MINIMUM SALARY.

	--11. FIND THE AVERAGE SALARY OF A PERSON WHO BELONGS TO AHMEDABAD CITY.

	--12. PRODUCE OUTPUT LIKE: <PERSONNAME> LIVES IN <CITY> AND WORKS IN <DEPARTMENTNAME> DEPARTMENT. (IN SINGLE COLUMN)


--PART – B:


	--1. PRODUCE OUTPUT LIKE: <PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY. (IN SINGLE COLUMN)

	--2. FIND CITY & DEPARTMENT WISE TOTAL, AVERAGE & MAXIMUM SALARIES.

	--3. FIND ALL PERSONS WHO DO NOT BELONG TO ANY DEPARTMENT.

	--4. FIND ALL DEPARTMENTS WHOSE TOTAL SALARY IS EXCEEDING 100000.

--PART – C:

	--1. LIST ALL DEPARTMENTS WHO HAVE NO PERSON.

	--2. LIST OUT DEPARTMENT NAMES IN WHICH MORE THAN TWO PERSONS ARE WORKING.

	--3. GIVE A 10% INCREMENT IN THE COMPUTER DEPARTMENT EMPLOYEE’S SALARY. (USE UPDATE)

