--LAB 11 (IMPLEMENT SQL JOINS)

--CREATE BELOW TABLES AS PER FOLLOWING DATA

--PART – A:

	--1. COMBINE INFORMATION FROM STUDENT AND RESULT TABLE USING CROSS JOIN OR CARTESIAN PRODUCT.

	--2. PERFORM INNER JOIN ON STUDENT AND RESULT TABLES.

	--3. PERFORM THE LEFT OUTER JOIN ON STUDENT AND RESULT TABLES.

	--4. PERFORM THE RIGHT OUTER JOIN ON STUDENT AND RESULT TABLES.

	--5. PERFORM THE FULL OUTER JOIN ON STUDENT AND RESULT TABLES.

	--6. DISPLAY RNO, NAME, BRANCH AND SPI OF ALL STUDENTS.

	--7. DISPLAY RNO, NAME, BRANCH AND SPI OF CE BRANCH’S STUDENT ONLY.

	--8. DISPLAY RNO, NAME, BRANCH AND SPI OF OTHER THAN EC BRANCH’S STUDENT ONLY.

	--9. DISPLAY AVERAGE RESULT OF EACH BRANCH.

	--10. DISPLAY AVERAGE RESULT OF CE AND ME BRANCH.

--PART – B:


	--1. DISPLAY AVERAGE RESULT OF EACH BRANCH AND SORT THEM IN ASCENDING ORDER BY SPI.

	--2. DISPLAY HIGHEST SPI FROM EACH BRANCH AND SORT THEM IN DESCENDING ORDER.

--PART – C:

	--1. RETRIEVE THE NAMES OF EMPLOYEE ALONG WITH THEIR MANAGER’S NAME FROM THE EMPLOYEE TABLE
